columnSuffix: null
contentColumnType: string
fieldGroup: 20e41d9d-a586-4d1a-b5ad-ce3572aa2fa5 # Globals
handle: footer
instructions: null
name: Footer
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1465847648
  columns:
    __assoc__:
      -
        - 144bff5e-94b1-4971-a645-14a75b6c17ac # Slogan
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 88b62b4d-d59b-44dd-a2ce-01633ea93cb9 # Socials
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 2823bcc1-a5ed-4a7e-9701-93851c22fc89 # Copyright
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_footer}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
