columnSuffix: null
contentColumnType: string
fieldGroup: fe10ca1e-b9b0-4764-a8ce-9d11827b9828 # Common
handle: project
instructions: null
name: Project
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 563122384
  columns:
    __assoc__:
      -
        - 4b0c469d-a3d8-458d-94ec-a4d75e7d5113 # Project Type
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e8fcf4aa-1cdc-49ad-8048-46bed34d2778 # Website
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 80a1b328-51fc-4279-b100-81fa2a22fb1c # Company
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 03256383-6fd4-4177-8a2f-21f8ed132eaf # Visit Project Toggle
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e99163f5-b2d2-4227-8e83-bdee821e3061 # Visit Disclaimer
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 2c5af258-38c5-4f55-a53f-51bfd3e8c429 # USPS
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c95eed35-ff61-47b8-b7da-6575c6cb70bf # Lead
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 8ae77031-641a-4b54-9f48-559ac4d9787a # Long Text
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 8d04658c-7a80-49e4-a3d0-e13134345b73 # Key Details
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70 # Images
        -
          __assoc__:
            -
              - width
              - ''
      -
        - e0e7f238-8f75-4da6-9e88-6cd94e2d2f85 # Images Darkmode
        -
          __assoc__:
            -
              - width
              - ''
      -
        - df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0 # Lighthouse
        -
          __assoc__:
            -
              - width
              - ''
      -
        - c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e # Lighthouse Doc
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_project}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
