defaultPlacement: end
enableVersioning: true
handle: successpages
name: Successpages
propagationMethod: all
siteSettings:
  3fcef9e7-61e0-496b-bb55-a3318f79c6c4: # Nico Fortino Deutsch
    enabledByDefault: true
    hasUrls: true
    template: other/_entry.twig
    uriFormat: 'successpages/{slug}'
  39beb36f-cf9a-4ac5-8eb5-17da62ed4cfa: # Nico Fortino
    enabledByDefault: true
    hasUrls: true
    template: other/_entry.twig
    uriFormat: 'successpages/{slug}'
structure:
  maxLevels: null
  uid: 0f9f1f14-5f3c-4f48-bb6a-ed94a4a119bf
type: structure
