defaultPlacement: end
enableVersioning: true
handle: vcard
name: vCard
propagationMethod: all
siteSettings:
  39beb36f-cf9a-4ac5-8eb5-17da62ed4cfa: # Nico Fortino
    enabledByDefault: true
    hasUrls: true
    template: vcard/_entry.twig
    uriFormat: vcard
type: single
