field: 7d3a9466-67b6-48b0-aeb6-c83eec97c608 # Inhaltsblöcke
fieldLayouts:
  a889f022-58ee-44a8-962b-9a55c810c59d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 77280f8b-c780-4d41-aa2a-5700ff4dd464 # Project Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caed4645-7b6e-4385-966c-4f5e52cb5b17
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f574e8e2-6077-4da6-8799-b4cee150659b
        userCondition: null
fields:
  77280f8b-c780-4d41-aa2a-5700ff4dd464: # Project Type
    columnSuffix: wkhhachz
    contentColumnType: boolean
    fieldGroup: null
    handle: projectType
    instructions: null
    name: 'Project Type'
    searchable: false
    settings:
      default: false
      offLabel: Developed
      onLabel: Maintained
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: projectGridDesktop
name: 'Project Grid Desktop'
sortOrder: 3
