field: 7d3a9466-67b6-48b0-aeb6-c83eec97c608 # Inhaltsblöcke
fieldLayouts:
  aecfbe57-534f-42c9-bb40-a99b3eb68669:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 86c14da8-48a5-4bc6-b2ba-be14d39644ea # More Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03fa842b-3f67-43d5-a5d4-cc8bea016d40
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 4d9ad22a-71a4-486c-8a17-4aa06b7202fb # Work
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0c84183-c742-479e-95ca-739b6cbc0a82
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 61b8d3da-15d5-4669-9ed6-74f1f5a45b60
        userCondition: null
fields:
  4d9ad22a-71a4-486c-8a17-4aa06b7202fb: # Work
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: work
    instructions: null
    name: Work
    searchable: false
    settings:
      allowSelfRelations: false
      branchLimit: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      selectionLabel: null
      showSiteMenu: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  86c14da8-48a5-4bc6-b2ba-be14d39644ea: # More Button
    columnSuffix: ydovebck
    contentColumnType: text
    fieldGroup: null
    handle: moreButton
    instructions: null
    name: 'More Button'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: projectGrid
name: 'Project Grid'
sortOrder: 2
