field: 7d3a9466-67b6-48b0-aeb6-c83eec97c608 # Inhaltsblöcke
fieldLayouts:
  b2c73111-04f7-4cd6-adeb-9587aea7e11a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 80a5d7e1-bfd1-4615-bbb3-8b7b66687b39 # Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 012428bb-b0e5-40a7-86fb-b539ca368f6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd13e7ba-d3ab-4b70-8886-15235540b6cd # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6546c31-6781-4902-80ad-41766f6130b1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de9cfe41-aa6d-4251-93ad-a66f676b856b # Send
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65de3098-4bdc-4a51-b149-fdff14ef3063
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 77e85646-ae3c-4596-9178-7eb54926e829 # Docs Download
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7915747-ab95-42cb-abc2-be02307f64b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3d8a1d1b-92f9-4fdf-94e5-b570de06f2aa
        userCondition: null
fields:
  77e85646-ae3c-4596-9178-7eb54926e829: # Docs Download
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: docsDownload
    instructions: null
    name: 'Docs Download'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  80a5d7e1-bfd1-4615-bbb3-8b7b66687b39: # Titel
    columnSuffix: wcnqbbax
    contentColumnType: text
    fieldGroup: null
    handle: titel
    instructions: null
    name: Titel
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  de9cfe41-aa6d-4251-93ad-a66f676b856b: # Send
    columnSuffix: uyboezmh
    contentColumnType: text
    fieldGroup: null
    handle: send
    instructions: null
    name: Send
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fd13e7ba-d3ab-4b70-8886-15235540b6cd: # Text
    columnSuffix: fsadlyvv
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
handle: whymeDocs
name: 'Whyme Docs'
sortOrder: 7
