changedFieldIndicator: 44943254
field: c0ecf69b-ca47-4742-99ff-eb31134aabb6 # Whyme Table
fieldLayouts:
  67a8b75c-021d-40e6-8481-443ff563f950:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73c45582-f13a-4798-9369-3cbbd3cdf022 # Company ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83fb0e4d-9b0d-4088-9fe9-4d898cf9bd96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2be97e32-03c7-4302-ac10-ead9b3bcff0d # Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f9e2a4d-c505-439f-a05a-25186ce5408f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00a75be5-ae54-4ef7-9884-0769fc4b9ea0 # Compay Person Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5246f3-27d6-4522-80f8-1ced67cbc33a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 11622e7c-3802-44c4-a67d-53c2ae3641b3 # Company Documents
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2df4f022-bd86-42ca-ae8b-5ff3cc56fcf4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e33b8e9-4881-49dd-8031-e6cab8dad926
        userCondition: null
fields:
  00a75be5-ae54-4ef7-9884-0769fc4b9ea0: # Compay Person Name
    columnSuffix: kvorqeqc
    contentColumnType: text
    fieldGroup: null
    handle: compayPersonName
    instructions: null
    name: 'Compay Person Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2be97e32-03c7-4302-ac10-ead9b3bcff0d: # Company
    columnSuffix: zmkrneys
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: null
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  73c45582-f13a-4798-9369-3cbbd3cdf022: # Company ID
    columnSuffix: mzqwqrmv
    contentColumnType: text
    fieldGroup: null
    handle: companyId
    instructions: null
    name: 'Company ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  11622e7c-3802-44c4-a67d-53c2ae3641b3: # Company Documents
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: companyDocuments
    instructions: null
    name: 'Company Documents'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
