changedFieldIndicator: 1301023239
field: c0ecf69b-ca47-4742-99ff-eb31134aabb6 # Whyme Table
fieldLayouts:
  67a8b75c-021d-40e6-8481-443ff563f950:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 73c45582-f13a-4798-9369-3cbbd3cdf022 # Company ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83fb0e4d-9b0d-4088-9fe9-4d898cf9bd96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2be97e32-03c7-4302-ac10-ead9b3bcff0d # Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f9e2a4d-c505-439f-a05a-25186ce5408f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 00a75be5-ae54-4ef7-9884-0769fc4b9ea0 # Compay Person Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c5246f3-27d6-4522-80f8-1ced67cbc33a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e33b8e9-4881-49dd-8031-e6cab8dad926
        userCondition: null
fields:
  00a75be5-ae54-4ef7-9884-0769fc4b9ea0: # Compay Person Name
    columnSuffix: kvorqeqc
    contentColumnType: text
    fieldGroup: null
    handle: compayPersonName
    instructions: null
    name: 'Compay Person Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2be97e32-03c7-4302-ac10-ead9b3bcff0d: # Company
    columnSuffix: zmkrneys
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: null
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  73c45582-f13a-4798-9369-3cbbd3cdf022: # Company ID
    columnSuffix: mzqwqrmv
    contentColumnType: text
    fieldGroup: null
    handle: companyId
    instructions: null
    name: 'Company ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
