changedFieldIndicator: 1514966409
field: 54f28729-6ed2-44ae-bcf5-80a3c33f9a3b # Multitext
fieldLayouts:
  77f2a3f4-e736-4e74-9772-fb243e0895b8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 43177c04-ef38-4ad1-9145-e7f6846de1ad # Textblock
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ec993865-dc42-46d2-aeaf-034d8ed3552b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 409b7068-cdb7-4c05-a325-5debc48bcc4c
        userCondition: null
fields:
  43177c04-ef38-4ad1-9145-e7f6846de1ad: # Textblock
    columnSuffix: fycownnk
    contentColumnType: text
    fieldGroup: null
    handle: textblock
    instructions: null
    name: Textblock
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
