changedFieldIndicator: 2047813198
field: ff043439-6dc6-4d85-ad23-1d430fd1d0ea # Project
fieldLayouts:
  a7421637-2389-402d-a1a8-03d92b2d0bff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: e8fcf4aa-1cdc-49ad-8048-46bed34d2778 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c252035d-0953-45e0-a978-c2cb21fdbb78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80a1b328-51fc-4279-b100-81fa2a22fb1c # Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80fd3817-4068-43b7-b547-310ffc3b5ef3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c5af258-38c5-4f55-a53f-51bfd3e8c429 # USPS
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4197dc5e-a7d4-41c5-9bd0-70096d65fcd5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c95eed35-ff61-47b8-b7da-6575c6cb70bf # Lead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae11c3e3-12c4-4d7f-9006-23a55d18b9ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8b359e0-1d3f-4974-98a2-ff4f83d63cef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0 # Lighthouse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa3cef70-951d-457a-8657-c38c5daefb57
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e # Lighthouse Doc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ae481a-2048-47c5-9d9f-201f63178e24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a671a929-0354-44b9-8ded-1c4b6f00f403
        userCondition: null
fields:
  0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2c5af258-38c5-4f55-a53f-51bfd3e8c429: # USPS
    columnSuffix: ocvepgxn
    contentColumnType: text
    fieldGroup: null
    handle: usps
    instructions: null
    name: USPS
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Title
                -
                  - handle
                  - title
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Item
                -
                  - handle
                  - item
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  80a1b328-51fc-4279-b100-81fa2a22fb1c: # Company
    columnSuffix: hkmsiejb
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: null
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e: # Lighthouse Doc
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: lighthouseDoc
    instructions: null
    name: 'Lighthouse Doc'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c95eed35-ff61-47b8-b7da-6575c6cb70bf: # Lead
    columnSuffix: rkmyfkkh
    contentColumnType: text
    fieldGroup: null
    handle: lead
    instructions: null
    name: Lead
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0: # Lighthouse
    columnSuffix: myxpgfeu
    contentColumnType: text
    fieldGroup: null
    handle: lighthouse
    instructions: null
    name: Lighthouse
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Performance
                -
                  - handle
                  - performance
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Accesability
                -
                  - handle
                  - accesability
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Best Practices'
                -
                  - handle
                  - bestPractices
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - SEO
                -
                  - handle
                  - seo
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
            -
              - col4
              - ''
      maxRows: null
      minRows: null
      staticRows: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  e8fcf4aa-1cdc-49ad-8048-46bed34d2778: # Website
    columnSuffix: cbaheixw
    contentColumnType: text
    fieldGroup: null
    handle: website
    instructions: null
    name: Website
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
