changedFieldIndicator: 1095738172
field: ff043439-6dc6-4d85-ad23-1d430fd1d0ea # Project
fieldLayouts:
  a7421637-2389-402d-a1a8-03d92b2d0bff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b0c469d-a3d8-458d-94ec-a4d75e7d5113 # Project Type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e44b7721-267d-43c0-9d95-f4ec4ddf4c3b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e8fcf4aa-1cdc-49ad-8048-46bed34d2778 # Website
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c252035d-0953-45e0-a978-c2cb21fdbb78
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 80a1b328-51fc-4279-b100-81fa2a22fb1c # Company
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80fd3817-4068-43b7-b547-310ffc3b5ef3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 03256383-6fd4-4177-8a2f-21f8ed132eaf # Visit Project Toggle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bde75423-7eb7-4461-a18d-5ea35cf39e0e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e99163f5-b2d2-4227-8e83-bdee821e3061 # Visit Disclaimer
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fee6e713-e1bf-43c7-a685-099ea8944d17
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c5af258-38c5-4f55-a53f-51bfd3e8c429 # USPS
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4197dc5e-a7d4-41c5-9bd0-70096d65fcd5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c95eed35-ff61-47b8-b7da-6575c6cb70bf # Lead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae11c3e3-12c4-4d7f-9006-23a55d18b9ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ae77031-641a-4b54-9f48-559ac4d9787a # Long Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d1198a6d-9ce0-4567-ad6f-02c794bcc559
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d04658c-7a80-49e4-a3d0-e13134345b73 # Key Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ce287ee-a023-46d4-ac5e-c2caed92af12
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8b359e0-1d3f-4974-98a2-ff4f83d63cef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e0e7f238-8f75-4da6-9e88-6cd94e2d2f85 # Images Darkmode
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ccc6d8d-6b92-4190-8d84-92f8d9820a23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0 # Lighthouse
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa3cef70-951d-457a-8657-c38c5daefb57
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e # Lighthouse Doc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f4ae481a-2048-47c5-9d9f-201f63178e24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a671a929-0354-44b9-8ded-1c4b6f00f403
        userCondition: null
fields:
  0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2c5af258-38c5-4f55-a53f-51bfd3e8c429: # USPS
    columnSuffix: ocvepgxn
    contentColumnType: text
    fieldGroup: null
    handle: usps
    instructions: null
    name: USPS
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Title
                -
                  - handle
                  - title
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Item
                -
                  - handle
                  - item
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  4b0c469d-a3d8-458d-94ec-a4d75e7d5113: # Project Type
    columnSuffix: ifuyeapi
    contentColumnType: string(18)
    fieldGroup: null
    handle: projectType
    instructions: null
    name: 'Project Type'
    searchable: false
    settings:
      columnType: null
      options:
        -
          __assoc__:
            -
              - label
              - Developed
            -
              - value
              - developed
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Improved & Maintained'
            -
              - value
              - improvedMaintained
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  8ae77031-641a-4b54-9f48-559ac4d9787a: # Long Text
    columnSuffix: avpnucfy
    contentColumnType: text
    fieldGroup: null
    handle: longText
    instructions: null
    name: 'Long Text'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  8d04658c-7a80-49e4-a3d0-e13134345b73: # Key Details
    columnSuffix: uybtfqhx
    contentColumnType: text
    fieldGroup: null
    handle: keyDetails
    instructions: null
    name: 'Key Details'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Detail
                -
                  - handle
                  - detail
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  80a1b328-51fc-4279-b100-81fa2a22fb1c: # Company
    columnSuffix: hkmsiejb
    contentColumnType: text
    fieldGroup: null
    handle: company
    instructions: null
    name: Company
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  03256383-6fd4-4177-8a2f-21f8ed132eaf: # Visit Project Toggle
    columnSuffix: qoercirb
    contentColumnType: boolean
    fieldGroup: null
    handle: visitProjectOn
    instructions: null
    name: 'Visit Project Toggle'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Lightswitch
  c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e: # Lighthouse Doc
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: lighthouseDoc
    instructions: null
    name: 'Lighthouse Doc'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c95eed35-ff61-47b8-b7da-6575c6cb70bf: # Lead
    columnSuffix: rkmyfkkh
    contentColumnType: text
    fieldGroup: null
    handle: lead
    instructions: null
    name: Lead
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: null
      removeEmptyTags: false
      removeInlineStyles: false
      removeNbsp: false
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: site
    type: craft\redactor\Field
  df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0: # Lighthouse
    columnSuffix: myxpgfeu
    contentColumnType: text
    fieldGroup: null
    handle: lighthouse
    instructions: null
    name: Lighthouse
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Performance
                -
                  - handle
                  - performance
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Accesability
                -
                  - handle
                  - accesability
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col3
            -
              __assoc__:
                -
                  - heading
                  - 'Best Practices'
                -
                  - handle
                  - bestPractices
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col4
            -
              __assoc__:
                -
                  - heading
                  - SEO
                -
                  - handle
                  - seo
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
            -
              - col3
              - ''
            -
              - col4
              - ''
      maxRows: null
      minRows: null
      staticRows: true
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Table
  e0e7f238-8f75-4da6-9e88-6cd94e2d2f85: # Images Darkmode
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imagesDarkmode
    instructions: null
    name: 'Images Darkmode'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:5acbfce0-0c16-404d-bdf8-1b7185ed660a' # Uploads
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e8fcf4aa-1cdc-49ad-8048-46bed34d2778: # Website
    columnSuffix: cbaheixw
    contentColumnType: text
    fieldGroup: null
    handle: website
    instructions: null
    name: Website
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  e99163f5-b2d2-4227-8e83-bdee821e3061: # Visit Disclaimer
    columnSuffix: ktrnzaav
    contentColumnType: text
    fieldGroup: null
    handle: visitMsg
    instructions: null
    name: 'Visit Disclaimer'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
