dateModified: 1725442241
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      heading: Projects
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:1c5bd7ca-883b-4808-b311-7425ff5d9b00' # Projects
      tableAttributes:
        - 'field:f4c476d5-c7ea-4540-8e96-6880d7382f5a' # Project Number
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Website
      type: heading
    -
      key: 'section:6819ac29-167a-4d1e-960c-4e35b9e29e2c' # Website
      type: native
    -
      heading: 'Legal Section'
      type: heading
    -
      key: 'section:09f0f218-7f4b-43e5-8430-79e3f9cfdb4c' # Legal
      type: native
email:
  fromEmail: nico@fortino.ch
  fromName: Nico
  transportType: craft\mail\transportadapters\Sendmail
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: uploads
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a6a4808-0001-4bf3-9ee9-9b82be6e7da0: Header # Header
    0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70: Images # Images
    0fe360b3-6a5c-40b5-82ad-1a7b95e24bb1: 'System Translations' # System Translations
    1b87bb8c-7437-45cd-ba6c-dda757010806: E-Mail # E-Mail
    1c5bd7ca-883b-4808-b311-7425ff5d9b00: Projects # Projects
    2a4e471b-0a46-4344-91b4-8f8ea1f2d816: Message # Message
    2ad51318-063a-4905-a994-0bc1fb82d356: 'Public Schema' # Public Schema
    2c2e56d1-e9c7-44fd-ab6a-3d2fe9755ac9: Success # Success
    2c5af258-38c5-4f55-a53f-51bfd3e8c429: USPS # USPS
    3d5edf3c-eda8-498e-ac75-94245e775112: Footer # Footer
    3e069843-7cda-4080-96c0-7d1ab55460a2: Nico # Nico
    3e4a020a-8ec6-4ab7-a4d8-6ad3cb08f660: 'Hi, I am' # Hi, I am
    3ef06bed-e337-4554-9c87-36a4a4cdf5a7: Lead # Lead
    3f9ca21a-d5e5-4548-a759-98615640646e: 'SEO Default' # SEO Default
    3fcef9e7-61e0-496b-bb55-a3318f79c6c4: 'Nico Fortino Deutsch' # Nico Fortino Deutsch
    4b0c469d-a3d8-458d-94ec-a4d75e7d5113: 'Project Type' # Project Type
    4d9ad22a-71a4-486c-8a17-4aa06b7202fb: Work # Work
    5acbfce0-0c16-404d-bdf8-1b7185ed660a: Uploads # Uploads
    05b1c09b-200c-4d6b-bfdb-bc4300f1b579: 'Project Grid' # Project Grid
    5cb1ee9e-5f24-409e-b6b4-1f27aaaf02d4: 'Project Color' # Project Color
    6f0a57bf-3450-4fb2-9512-a4e0eda1db1d: 'Meta Info' # Meta Info
    6feb5671-1f19-4004-bd05-df4d3a45f04a: Beschreibung # Beschreibung
    7d3a9466-67b6-48b0-aeb6-c83eec97c608: Inhaltsblöcke # Inhaltsblöcke
    8d04658c-7a80-49e4-a3d0-e13134345b73: 'Key Details' # Key Details
    8f9812d2-2102-43ac-8ef1-21923dc442e7: Default # Default
    09f0f218-7f4b-43e5-8430-79e3f9cfdb4c: Legal # Legal
    9f3d19d1-3b06-4cdf-8c6b-70c688ca8d69: Home # Home
    13b9bb0a-95e4-4c8c-a153-c137213cbcc6: SEO # SEO
    20e41d9d-a586-4d1a-b5ad-ce3572aa2fa5: Globals # Globals
    27cc7330-872f-4020-834b-ba69bd1d14a0: Contact # Contact
    028c7152-a72a-4eeb-9873-2a588c93ac15: Performance # Performance
    36bcb1ac-1912-493b-bdfc-3ea2c89e5567: Send # Send
    39beb36f-cf9a-4ac5-8eb5-17da62ed4cfa: 'Nico Fortino' # Nico Fortino
    47fe1798-f313-486b-b362-d2d3687bb528: Footer # Footer
    51c6826d-9df2-4942-a2e4-4210c13a1782: 'Project Grid Desktop' # Project Grid Desktop
    54f28729-6ed2-44ae-bcf5-80a3c33f9a3b: Multitext # Multitext
    66afba17-355c-41a0-b3f8-fc366a51ebf3: Hero # Hero
    66ff83f7-3ee7-4308-a0f3-e30bd3b3b32f: Home # Home
    80a1b328-51fc-4279-b100-81fa2a22fb1c: Company # Company
    86c14da8-48a5-4bc6-b2ba-be14d39644ea: 'More Button' # More Button
    88b62b4d-d59b-44dd-a2ce-01633ea93cb9: Socials # Socials
    128f1efd-9e3e-480d-8af3-53ec285156b1: Dataprotection # Dataprotection
    144bff5e-94b1-4971-a645-14a75b6c17ac: Slogan # Slogan
    218d8979-17f4-4679-b012-92e6ef852553: Memes # Memes
    227a9ae2-cd4d-4643-897f-d4ac6d783162: Nav # Nav
    2823bcc1-a5ed-4a7e-9701-93851c22fc89: Copyright # Copyright
    5480a795-1e8a-4a68-bdcc-1828da84ac66: 'Loading Message' # Loading Message
    6819ac29-167a-4d1e-960c-4e35b9e29e2c: Website # Website
    43177c04-ef38-4ad1-9145-e7f6846de1ad: Textblock # Textblock
    0066189a-4042-4e22-bfd6-6886d33fb469: 'Key Details' # Key Details
    79561ee7-69e1-4376-9ff6-845290991754: Error # Error
    96634e98-38ff-4af4-be4d-a8239d1aed6b: Accesability # Accesability
    710978b0-e1c7-4e88-8836-01d9d5e1545b: Standard # Standard
    929529d1-d267-49c7-84d4-aae762b8d3ce: 'Social Image' # Social Image
    03256383-6fd4-4177-8a2f-21f8ed132eaf: 'Visit Project Toggle' # Visit Project Toggle
    24595093-d773-46cb-8e2d-94fa3047e696: Name # Name
    78334100-b3bd-4b9f-aa08-b3b24f027447: 'More Projects' # More Projects
    87278682-c4ad-4783-9262-b4ad2533f76b: Header # Header
    a3863cb8-ba1c-44f0-90bd-3df22d44535a: 'Not Found' # Not Found
    bb1c7b43-4c8a-4e94-aad9-aec8f4c1a9e1: Keywords # Keywords
    bc2e72bc-09fb-4792-90eb-95db2a0f0d15: Subject # Subject
    c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e: 'Lighthouse Doc' # Lighthouse Doc
    c5b719bd-6f79-415b-92cb-9ec7d79dcfc3: Titel # Titel
    c95eed35-ff61-47b8-b7da-6575c6cb70bf: Lead # Lead
    c65316b9-b426-4343-ac32-6a571787a8c9: 'Best Practices' # Best Practices
    d24a29e6-d389-4d74-a3e9-0d4ea6c70f79: Default # Default
    d32f8599-4ed4-4a93-b822-1634f69b79fb: Titel # Titel
    d36d8b9e-25bd-4ad0-b272-3f6a873eae3f: ProjectsMaintained # ProjectsMaintained
    d417dac4-c9bd-468c-a793-615fd214ef64: Legallinks # Legallinks
    d548142e-cce6-4a62-af0e-119193fd33be: 'System Translations' # System Translations
    df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0: Lighthouse # Lighthouse
    e0e7f238-8f75-4da6-9e88-6cd94e2d2f85: 'Images Darkmode' # Images Darkmode
    e2f03771-3613-4b28-864c-b37abe512794: 'Not Found' # Not Found
    e3af7e87-51b6-40d5-abc7-360c475923ee: 'Visit Project' # Visit Project
    e3e3947d-eb8b-4c62-8c1d-923a56951ef1: Share # Share
    e8fcf4aa-1cdc-49ad-8048-46bed34d2778: Website # Website
    e487c058-76a1-41cc-af91-743b411e146b: Text # Text
    e99163f5-b2d2-4227-8e83-bdee821e3061: 'Visit Disclaimer' # Visit Disclaimer
    eb53d36d-66e7-4ac1-b4e8-61f7ec736021: ProjectsDeveloped # ProjectsDeveloped
    ee08378b-d81d-4a46-9a80-eb29a6a5e660: 'Lighthouse Report' # Lighthouse Report
    f0bb9251-9d2c-4024-a994-8354d1ff8003: Logo # Logo
    f2b3f032-5c1a-4c64-8d26-a10ecbfe33d2: 'Let''s Talk' # Let's Talk
    f4c476d5-c7ea-4540-8e96-6880d7382f5a: 'Project Number' # Project Number
    fe10ca1e-b9b0-4764-a8ce-9d11827b9828: Common # Common
    ff043439-6dc6-4d85-ad23-1d430fd1d0ea: Project # Project
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from nicofortino.ch'
      successFlashMessage: 'Your message has been sent.'
      toEmail: nico@fortino.ch
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: ''
      confirmationTemplate: ''
      enableConfirmationEmail: ''
      enableDatabase: '1'
      enableRecaptchaOverride: ''
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: ''
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: ''
      recaptchaSecretKey: ''
      recaptchaSiteKey: ''
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '5'
      recaptchaUrl: ''
      recaptchaVerificationUrl: ''
      recaptchaVersion: ''
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
    settings:
      checkInvalidLogins: false
      enableCpProtection: false
      enabled: false
      forcedRedirect: ''
      invalidLoginWindowDuration: '3600'
      loginPath: login
      maxInvalidLogins: 10
      password: 'bsj!209jdkn?'
      siteSettings:
        __assoc__:
          -
            - EN
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
          -
            - DE
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
      template: ''
      useRemoteIp: false
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: Nico
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
