dateModified: 1746437476
elementSources:
  craft\elements\Entry:
    -
      key: '*'
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: singles
      tableAttributes:
        - link
      type: native
    -
      heading: Projects
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:1c5bd7ca-883b-4808-b311-7425ff5d9b00' # Projects
      tableAttributes:
        - 'field:f4c476d5-c7ea-4540-8e96-6880d7382f5a' # Project Number
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Website
      type: heading
    -
      key: 'section:6819ac29-167a-4d1e-960c-4e35b9e29e2c' # Website
      type: native
    -
      heading: 'Legal Section'
      type: heading
    -
      key: 'section:09f0f218-7f4b-43e5-8430-79e3f9cfdb4c' # Legal
      type: native
email:
  fromEmail: noreply@nicofortino.ch
  fromName: 'Nico Fortino'
  replyToEmail: nico@fortino.ch
  template: null
  transportSettings:
    host: mail.cyon.ch
    password: '(B,YZtqbMf?G6('
    port: '465'
    useAuthentication: '1'
    username: noreply@nicofortino.ch
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: uploads
    type: craft\fs\Local
    url: '@web/uploads'
meta:
  __names__:
    0a6a4808-0001-4bf3-9ee9-9b82be6e7da0: Header # Header
    00a75be5-ae54-4ef7-9884-0769fc4b9ea0: 'Compay Person Name' # Compay Person Name
    0bed584b-8cb1-4215-b883-131b806cfe6f: 'Whyme Hero' # Whyme Hero
    0e3e5e64-bdfa-44a3-9ba6-e67c212ccb70: Images # Images
    0fe360b3-6a5c-40b5-82ad-1a7b95e24bb1: 'System Translations' # System Translations
    1b87bb8c-7437-45cd-ba6c-dda757010806: E-Mail # E-Mail
    1ba1185a-1454-4140-ad60-9a8d0de7bdd1: Default # Default
    1c5bd7ca-883b-4808-b311-7425ff5d9b00: Projects # Projects
    2a4e471b-0a46-4344-91b4-8f8ea1f2d816: Message # Message
    2ad51318-063a-4905-a994-0bc1fb82d356: 'Public Schema' # Public Schema
    2be97e32-03c7-4302-ac10-ead9b3bcff0d: Company # Company
    2c1a0ce7-6b1a-4bfa-b04e-341f5b28fa78: Lead2 # Lead2
    2c5af258-38c5-4f55-a53f-51bfd3e8c429: USPS # USPS
    2ee54c87-988b-4546-bd69-419027d96dc2: Titel2 # Titel2
    2fb531a6-ab83-4d7b-b4e2-81d5e2c53538: Text # Text
    3b7be32f-585b-4e6b-aab6-91365b28b881: 'Whyme Projects' # Whyme Projects
    3d5edf3c-eda8-498e-ac75-94245e775112: Footer # Footer
    3e069843-7cda-4080-96c0-7d1ab55460a2: Nico # Nico
    3e4a020a-8ec6-4ab7-a4d8-6ad3cb08f660: 'Hi, I am' # Hi, I am
    3ef06bed-e337-4554-9c87-36a4a4cdf5a7: Lead # Lead
    3f9ca21a-d5e5-4548-a759-98615640646e: 'SEO Default' # SEO Default
    3fcef9e7-61e0-496b-bb55-a3318f79c6c4: 'Nico Fortino Deutsch' # Nico Fortino Deutsch
    4b0c469d-a3d8-458d-94ec-a4d75e7d5113: 'Project Type' # Project Type
    4d9ad22a-71a4-486c-8a17-4aa06b7202fb: Work # Work
    5acbfce0-0c16-404d-bdf8-1b7185ed660a: Uploads # Uploads
    05b1c09b-200c-4d6b-bfdb-bc4300f1b579: 'Project Grid' # Project Grid
    5cb1ee9e-5f24-409e-b6b4-1f27aaaf02d4: 'Project Color' # Project Color
    6f0a57bf-3450-4fb2-9512-a4e0eda1db1d: 'Meta Info' # Meta Info
    6feb5671-1f19-4004-bd05-df4d3a45f04a: Beschreibung # Beschreibung
    7d3a9466-67b6-48b0-aeb6-c83eec97c608: Inhaltsblöcke # Inhaltsblöcke
    7d4fce12-e807-4d16-91ec-2d969dda882b: Send # Send
    7d7834cd-5148-44ee-a839-4071ddb06fb6: Back # Back
    8abc142f-873f-4a19-8a90-30e41602f4e2: Projects # Projects
    8ae77031-641a-4b54-9f48-559ac4d9787a: 'Long Text' # Long Text
    8d04658c-7a80-49e4-a3d0-e13134345b73: 'Key Details' # Key Details
    8f9812d2-2102-43ac-8ef1-21923dc442e7: Default # Default
    09f0f218-7f4b-43e5-8430-79e3f9cfdb4c: Legal # Legal
    9f3d19d1-3b06-4cdf-8c6b-70c688ca8d69: Home # Home
    13b9bb0a-95e4-4c8c-a153-c137213cbcc6: SEO # SEO
    20e41d9d-a586-4d1a-b5ad-ce3572aa2fa5: Globals # Globals
    27cc7330-872f-4020-834b-ba69bd1d14a0: Contact # Contact
    028c7152-a72a-4eeb-9873-2a588c93ac15: Performance # Performance
    31e077af-18ee-4383-957c-7a37e0f27e19: Successpage # Successpage
    36bcb1ac-1912-493b-bdfc-3ea2c89e5567: Send # Send
    39beb36f-cf9a-4ac5-8eb5-17da62ed4cfa: 'Nico Fortino' # Nico Fortino
    47fe1798-f313-486b-b362-d2d3687bb528: Footer # Footer
    51c6826d-9df2-4942-a2e4-4210c13a1782: 'Project Grid Desktop' # Project Grid Desktop
    54f28729-6ed2-44ae-bcf5-80a3c33f9a3b: Multitext # Multitext
    66afba17-355c-41a0-b3f8-fc366a51ebf3: Hero # Hero
    66ff83f7-3ee7-4308-a0f3-e30bd3b3b32f: Home # Home
    70e71cb8-9ff8-49f7-935e-c5f6bc4a40ff: Feedbackset # Feedbackset
    73c45582-f13a-4798-9369-3cbbd3cdf022: 'Company ID' # Company ID
    80a1b328-51fc-4279-b100-81fa2a22fb1c: Company # Company
    80a5d7e1-bfd1-4615-bbb3-8b7b66687b39: Titel # Titel
    80f1914b-ac07-4f16-868c-7c0a467e9175: Textfield # Textfield
    84bc30dc-f84f-4aa7-9c00-163514f8ce89: Lead # Lead
    86c14da8-48a5-4bc6-b2ba-be14d39644ea: 'More Button' # More Button
    88b62b4d-d59b-44dd-a2ce-01633ea93cb9: Socials # Socials
    95effa97-a97a-46fa-9d89-34600e0e7896: Checkboxes # Checkboxes
    108e9664-ae99-4934-b153-0b3344093d56: vCard # vCard
    128f1efd-9e3e-480d-8af3-53ec285156b1: Dataprotection # Dataprotection
    144bff5e-94b1-4971-a645-14a75b6c17ac: Slogan # Slogan
    218d8979-17f4-4679-b012-92e6ef852553: Memes # Memes
    227a9ae2-cd4d-4643-897f-d4ac6d783162: Nav # Nav
    2823bcc1-a5ed-4a7e-9701-93851c22fc89: Copyright # Copyright
    3024c011-3482-4695-9a1b-43bee27b39e3: Successpage # Successpage
    5480a795-1e8a-4a68-bdcc-1828da84ac66: 'Loading Message' # Loading Message
    6819ac29-167a-4d1e-960c-4e35b9e29e2c: Website # Website
    11622e7c-3802-44c4-a67d-53c2ae3641b3: 'Company Documents' # Company Documents
    43177c04-ef38-4ad1-9145-e7f6846de1ad: Textblock # Textblock
    65675aae-84e7-458d-9bd3-b6685beb2d36: 'Titel 3' # Titel 3
    0066189a-4042-4e22-bfd6-6886d33fb469: 'Key Details' # Key Details
    96634e98-38ff-4af4-be4d-a8239d1aed6b: Accesability # Accesability
    275730ff-455d-4337-a450-e3d206580f0d: Text # Text
    710978b0-e1c7-4e88-8836-01d9d5e1545b: Standard # Standard
    929529d1-d267-49c7-84d4-aae762b8d3ce: 'Social Image' # Social Image
    03256383-6fd4-4177-8a2f-21f8ed132eaf: 'Visit Project Toggle' # Visit Project Toggle
    5364899e-5761-4c2f-b657-586e0ac81151: 'Github Repo not Found' # Github Repo not Found
    24595093-d773-46cb-8e2d-94fa3047e696: Name # Name
    78334100-b3bd-4b9f-aa08-b3b24f027447: 'More Projects' # More Projects
    82632312-e15a-4ac3-a31b-2f450c25eac5: Successpages # Successpages
    87278682-c4ad-4783-9262-b4ad2533f76b: Header # Header
    a6f26db1-a0ed-43d7-8d19-e47690efa35f: Projects # Projects
    a3863cb8-ba1c-44f0-90bd-3df22d44535a: 'Not Found' # Not Found
    ae8c300f-4295-491c-9ee6-ba4fc520ecff: Titel # Titel
    b1dd71f9-807b-443d-b3c9-27145f15e080: 'VCard File' # VCard File
    b1df1d43-c25c-48c7-b4f0-f15efae5be56: Titel # Titel
    b3f04e87-1f2e-4af8-b26a-34b9f4741c01: vCard # vCard
    bb1c7b43-4c8a-4e94-aad9-aec8f4c1a9e1: Keywords # Keywords
    bc2e72bc-09fb-4792-90eb-95db2a0f0d15: Subject # Subject
    c0ecf69b-ca47-4742-99ff-eb31134aabb6: 'Whyme Table' # Whyme Table
    c085eb9c-a4ad-42d4-8d8b-b1bb67a1be5e: 'Lighthouse Doc' # Lighthouse Doc
    c5b719bd-6f79-415b-92cb-9ec7d79dcfc3: Titel # Titel
    c95eed35-ff61-47b8-b7da-6575c6cb70bf: Lead # Lead
    c65316b9-b426-4343-ac32-6a571787a8c9: 'Best Practices' # Best Practices
    d0d8c2a6-f2cb-47de-bcd5-072c3879b5cf: Titel # Titel
    d24a29e6-d389-4d74-a3e9-0d4ea6c70f79: Default # Default
    d32f8599-4ed4-4a93-b822-1634f69b79fb: Titel # Titel
    d36d8b9e-25bd-4ad0-b272-3f6a873eae3f: ProjectsMaintained # ProjectsMaintained
    d417dac4-c9bd-468c-a793-615fd214ef64: Legallinks # Legallinks
    d145653d-40ab-46ca-b2eb-4eed75100e52: Successpage # Successpage
    d548142e-cce6-4a62-af0e-119193fd33be: 'System Translations' # System Translations
    de9cfe41-aa6d-4251-93ad-a66f676b856b: Send # Send
    df5a9729-4d8c-4f3a-9c5e-e71e9a2b52d0: Lighthouse # Lighthouse
    e0e7f238-8f75-4da6-9e88-6cd94e2d2f85: 'Images Darkmode' # Images Darkmode
    e2f03771-3613-4b28-864c-b37abe512794: 'Not Found' # Not Found
    e3af7e87-51b6-40d5-abc7-360c475923ee: 'Visit Project' # Visit Project
    e3e3947d-eb8b-4c62-8c1d-923a56951ef1: Share # Share
    e8fcf4aa-1cdc-49ad-8048-46bed34d2778: Website # Website
    e91ba2f0-fcb5-4faa-9793-80ba7701b1b6: V-Card # V-Card
    e94a5430-0995-4134-9a2a-6f5a93e071a8: 'Github Repo' # Github Repo
    e263b7b0-7549-4a8d-b333-4684bff8c9e4: Lead # Lead
    e487c058-76a1-41cc-af91-743b411e146b: Text # Text
    e99163f5-b2d2-4227-8e83-bdee821e3061: 'Visit Disclaimer' # Visit Disclaimer
    eb53d36d-66e7-4ac1-b4e8-61f7ec736021: ProjectsDeveloped # ProjectsDeveloped
    ec4efe28-7dfd-466a-9f76-04a6fb94ec7b: 'Whyme Feedback' # Whyme Feedback
    ec27a81a-8c42-4df9-9abb-86aa060987dd: 'Whyme Docs' # Whyme Docs
    ee08378b-d81d-4a46-9a80-eb29a6a5e660: 'Lighthouse Report' # Lighthouse Report
    f0bb9251-9d2c-4024-a994-8354d1ff8003: Logo # Logo
    f2b3f032-5c1a-4c64-8d26-a10ecbfe33d2: 'Let''s Talk' # Let's Talk
    f4c476d5-c7ea-4540-8e96-6880d7382f5a: 'Project Number' # Project Number
    f4849839-63c0-4777-9f14-74b3bb6e05ce: Video # Video
    f9922586-37fd-47f6-b89a-319cff8c7cc5: Video # Video
    fba4e963-4deb-4fb3-91e2-b016ac189287: Poster # Poster
    fd13e7ba-d3ab-4b70-8886-15235540b6cd: Text # Text
    fe10ca1e-b9b0-4764-a8ce-9d11827b9828: Common # Common
    ff043439-6dc6-4d85-ad23-1d430fd1d0ea: Project # Project
    ffac0529-8eb0-464d-8d79-934e03f12147: Tag # Tag
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: ''
      prependSubject: ''
      successFlashMessage: 'Your message has been sent.'
      toEmail: nico@fortino.ch
  contact-form-extensions:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
    settings:
      confirmationSubject: 'Alle Bewerbungsunterlagen von Nico Fortino'
      confirmationTemplate: _emails/_whymeDocsRequest
      enableConfirmationEmail: '1'
      enableDatabase: '1'
      enableRecaptchaOverride: ''
      enableTemplateOverwrite: ''
      notificationTemplate: ''
      recaptcha: '1'
      recaptchaDataBadge: bottomright
      recaptchaDebug: ''
      recaptchaHideBadge: '1'
      recaptchaSecretKey: 6LeP7M0qAAAAADPTpgSi1bnOrWju5dXuDirROnva
      recaptchaSiteKey: 6LeP7M0qAAAAAMJ6EfwgZnb_yvCmpQ3UUBECDOvR
      recaptchaThreshold: '0.5'
      recaptchaTimeout: '5'
      recaptchaUrl: ''
      recaptchaVerificationUrl: ''
      recaptchaVersion: '3'
  knock-knock:
    edition: standard
    enabled: true
    schemaVersion: 1.1.1
    settings:
      checkInvalidLogins: false
      enableCpProtection: false
      enabled: false
      forcedRedirect: ''
      invalidLoginWindowDuration: '3600'
      loginPath: login
      maxInvalidLogins: 10
      password: 'bsj!209jdkn?'
      siteSettings:
        __assoc__:
          -
            - EN
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
          -
            - DE
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - password
                  - ''
                -
                  - template
                  - ''
      template: ''
      useRemoteIp: false
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: Nico
  retryDuration: null
  schemaVersion: 4.15.0.0
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
