fieldLayouts:
  a5ee7568-4f2d-4c59-a68a-b0b487e33464:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 75ed3c14-9134-460d-9b7c-8f8ebd842b71
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: f4c476d5-c7ea-4540-8e96-6880d7382f5a # Project Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5fd129c-032c-428e-b3ef-a7c6a785df09
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6f0a57bf-3450-4fb2-9512-a4e0eda1db1d # Meta Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50e0f9a7-bd19-4da8-b925-eb324cfcadfc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff043439-6dc6-4d85-ad23-1d430fd1d0ea # Project
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b799424e-96ad-4b30-b047-0e843df7c54e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 922d9b8c-2472-42b9-be11-d1b6010e072a
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 1c5bd7ca-883b-4808-b311-7425ff5d9b00 # Projects
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
